### ISSUE TITLE
ImportError: cannot import name 'LightGBMClassifier' in v0.18.1

### ISSUE THREAD

**Issue by tyler-romero** [Azure/mmlspark#694]
**Describe the bug**
When I try to load `LightGBMClassifier` with `from mmlspark import LightGBMClassifier`, I get the error: `ImportError: cannot import name 'LightGBMClassifier'`

It was working in my previous version of mmlspark (a dev version of 0.17), but since updating to 0.18.1, it no longer works.

**Info:**
 - MMLSpark Version: v0.18.1
 - Spark Version: 2.4.3
 - Spark Platform: Databricks (Runtime 5.5 LTS ML)

**Comment by imatiach-msft** [comment]
@tyler-romero the namespaces changed, I think it is now from mmlspark.lightgbm import LightGBMClassifier, FYI @mhamilton723 do we have a doc on which namespaces changed to where?

**Comment by tyler-romero** [comment]
Thanks! Found the new namespaces here: https://mmlspark.blob.core.windows.net/docs/0.18.1/pyspark/modules.html
