### ISSUE TITLE
java.lang.NoClassDefFoundError: Lcom/microsoft/ml/lightgbm/SWIGTYPE_p_int64_t

### ISSUE THREAD

**Issue by caozhanxu** [Azure/mmlspark#846]
**Describe the bug**
I use lightGBM in spark cluster, it will show follow error, what can I fix it ?

User class threw exception: java.lang.NoClassDefFoundError: Lcom/microsoft/ml/lightgbm/SWIGTYPE_p_int64_t;java.lang.NoClassDefFoundError: Lcom/microsoft/ml/lightgbm/SWIGTYPE_p_int64_t;
at java.lang.Class.getDeclaredFields0(Native Method)
at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
at java.lang.Class.getDeclaredField(Class.java:2068)
at java.io.ObjectStreamClass.getDeclaredSUID(ObjectStreamClass.java:1703)
at java.io.ObjectStreamClass.access$700(ObjectStreamClass.java:72)
at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:472)
at java.security.AccessController.doPrivileged(Native Method)
at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:472)
at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:369)
at java.io.ObjectOutputStream.writeClass(ObjectOutputStream.java:1213)
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1120)
at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:43)
at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:295)
at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:288)
at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:108)
at org.apache.spark.SparkContext.clean(SparkContext.scala:2325)
at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1.apply(RDD.scala:796)
at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1.apply(RDD.scala:795)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
at org.apache.spark.rdd.RDD.mapPartitions(RDD.scala:795)
at org.apache.spark.sql.Dataset.rdd$lzycompute(Dataset.scala:2585)
at org.apache.spark.sql.Dataset.rdd(Dataset.scala:2582)
at org.apache.spark.sql.Dataset.reduce(Dataset.scala:1460)
at com.microsoft.ml.spark.LightGBMBase$class.train(LightGBMBase.scala:51)
at com.microsoft.ml.spark.LightGBMClassifier.train(LightGBMClassifier.scala:23)
at com.microsoft.ml.spark.LightGBMClassifier.train(LightGBMClassifier.scala:23)
at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
at org.apache.spark.ml.Predictor.fit(Predictor.scala:82)
at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:153)
at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:149)
at scala.collection.Iterator$class.foreach(Iterator.scala:893)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
at scala.collection.IterableViewLike$Transformed$class.foreach(IterableViewLike.scala:44)
at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:37)
at org.apache.spark.ml.Pipeline.fit(Pipeline.scala:149)
at com.meituan.rc.recall5.supervisedModel.SupervisedModel_3_TreeModel$.main(SupervisedModel_3_TreeModel.scala:152)
at com.meituan.rc.recall5.supervisedModel.SupervisedModel_3_TreeModel.main(SupervisedModel_3_TreeModel.scala)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:660)
Caused by: java.lang.ClassNotFoundException: com.microsoft.ml.lightgbm.SWIGTYPE_p_int64_t
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 55 more

**Info (please complete the following information):**
 - MMLSpark Version: [0.18.1]
 - Spark Version [2.2.0]
 - Spark Platform [yarn cluster]

<dependency>
        <groupId>com.microsoft.ml.spark</groupId>
        <artifactId>mmlspark_2.11</artifactId>
        <version>0.18.1</version>
    </dependency>
    <dependency>
        <groupId>com.microsoft.ml.lightgbm</groupId>
        <artifactId>lightgbmlib</artifactId>
        <version>2.2.400</version>
    </dependency>

**Comment by caozhanxu** [comment]
the system of my cluser is centOS 6.5

**Comment by yunnern** [comment]
I met the similar problem, my error is 'java.lang.NoClassDefFoundError: Lcom/microsoft/ml/lightgbm/SWIGTYPE_p_void'. Any solutions here?

**Comment by imatiach-msft** [comment]
Sorry about the trouble you are having, not sure. Usually when I see this error it means that the lightgbm jar is not getting loaded somehow.

**Comment by JWenBin** [comment]
When I tried to update lightgbmlib from 2.2.350 to 3.2.110, I got this error too. 
        <dependency>
            <groupId>com.microsoft.ml.lightgbm</groupId>
            <artifactId>lightgbmlib</artifactId>
            
            <version>2.2.350</version>
        </dependency>

**Comment by gnayoaixgnaw** [comment]
> Sorry about the trouble you are having, not sure. Usually, when I see this error it means that the lightgbm jar is not getting loaded somehow.

I got the same error when I update lightgbmlib from 2.2.350 to 2.3.10, then I check 2.3.10's jar and find there is no class named SWIGTYPE_p_int64_t.class. it seems that this class existed in 2.2.350 but its name changed in 2.3.10. I think this is the reason why I got this error. For some reason, I can only use spark 2.0+ which means I can't use synapseml, so is there any new version of mmlspark jar that can correctly call 2.3.10's new function? I find the latest version of mmlspark is mmlspark_2.11-0.18.1 which is exactly what I am using now, its there any solution?

**Comment by ranadeepsingh** [comment]
We are closing this issue as it is caused by a dependency version mismatch when explicitly overriding the transitive lightgbmlib dependency. SynapseML bundles a specific, compatible version of lightgbmlib; overriding it with a different version leads to missing SWIG wrapper classes like SWIGTYPE_p_int64_t. Please allow SynapseML to pull in its matching lightgbmlib dependency automatically without manual version overrides.
