### ISSUE TITLE
I am getting this error when building light gbm model on spark on local node of my machine

### ISSUE THREAD

**Issue by swaritras** [Azure/mmlspark#325]
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Info] Trying to bind port 12401...
[LightGBM] [Info] Binding port 12401 succeeded
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Connecting to rank 3 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Info] Trying to bind port 12402...
[LightGBM] [Info] Binding port 12402 succeeded
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Connecting to rank 3 failed, waiting for 10000 milliseconds
[LightGBM] [Info] Listening...
[LightGBM] [Info] Listening...
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Info] Trying to bind port 12403...
[LightGBM] [Info] Binding port 12403 succeeded
[LightGBM] [Info] Listening...
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Info] Trying to bind port 12400...
[LightGBM] [Info] Binding port 12400 succeeded
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Info] Listening...
[LightGBM] [Info] Connected to rank 1
[LightGBM] [Info] Connected to rank 2
[LightGBM] [Info] Connected to rank 3
[LightGBM] [Info] Local rank: 0, total number of machines: 4
[Stage 6:>                                                          (0 + 4) / 4][LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Info] Connected to rank 0
[LightGBM] [Info] Connected to rank 1
[LightGBM] [Info] Connected to rank 2
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Info] Connected to rank 0
[LightGBM] [Info] Connected to rank 2
[LightGBM] [Info] Connected to rank 3
[LightGBM] [Info] Local rank: 3, total number of machines: 4
[LightGBM] [Info] Local rank: 1, total number of machines: 4
[LightGBM] [Info] Connected to rank 0
[LightGBM] [Info] Connected to rank 1
[LightGBM] [Info] Connected to rank 3
[LightGBM] [Info] Local rank: 2, total number of machines: 4
[LightGBM] [Fatal] Cannot construct Dataset since there are not useful features.                 It should be at least two unique rows.                 If the num_row (num_data) is small, you can set min_data=1 and min_data_in_bin=1 to fix this.                 Otherwise please make sure you are using the right dataset.
[LightGBM] [Info] Finished linking network in 0.000094 seconds
[LightGBM] [Fatal] Cannot construct Dataset since there are not useful features.                 It should be at least two unique rows.                 If the num_row (num_data) is small, you can set min_data=1 and min_data_in_bin=1 to fix this.                 Otherwise please make sure you are using the right dataset.
[LightGBM] [Info] Finished linking network in 0.000460 seconds
[LightGBM] [Fatal] Cannot construct Dataset since there are not useful features.                 It should be at least two unique rows.                 If the num_row (num_data) is small, you can set min_data=1 and min_data_in_bin=1 to fix this.                 Otherwise please make sure you are using the right dataset.
[LightGBM] [Info] Finished linking network in 9.965447 seconds
[LightGBM] [Fatal] Cannot construct Dataset since there are not useful features.                 It should be at least two unique rows.                 If the num_row (num_data) is small, you can set min_data=1 and min_data_in_bin=1 to fix this.                 Otherwise please make sure you are using the right dataset.
[LightGBM] [Info] Finished linking network in 0.002327 seconds
2018-06-21 18:29:37 ERROR Executor:91 - Exception in task 2.0 in stage 6.0 (TID 17)
java.lang.Exception: Dataset create call failed in LightGBM with error: Cannot construct Dataset since there are not useful features.                 It should be at least two unique rows.                 If the num_row (num_data) is small, you can set min_data=1 and min_data_in_bin=1 to fix this.                 Otherwise please make sure you are using the right dataset.

**Comment by imatiach-msft** [comment]
@swaritras I've seen this error before on very small datasets - the suggestion of setting the min_data and min_data_in_bin seemed to fix it for me:

```
java.lang.Exception: Dataset create call failed in LightGBM with error: Cannot construct Dataset since there are not useful features. It should be at least two unique rows. If the num_row (num_data) is small, you can set min_data=1 and min_data_in_bin=1 to fix this. Otherwise please make sure you are using the right dataset.
```


How large is your dataset?

**Comment by swaritras** [comment]
ok, now I set min_data and min_data_in_bin, I again I am getting problem:---Traceback (most recent call last):
  File "/home/xpms/workspace/spark-env/lib/python3.6/site-packages/pyspark/ml/wrapper.py", line 105, in __del__
    SparkContext._active_spark_context._gateway.detach(self._java_obj)
AttributeError: 'LightGBMClassifier' object has no attribute '_java_obj'

**Comment by imatiach-msft** [comment]
@swaritras this error looks very different... not sure what is going on, but it looks like the underlying scala/java part of our package is missing, how are you running or installing mmlspark?  It looks like you are now failing at a much earlier place than before

**Comment by imatiach-msft** [comment]
@swaritras can this issue be closed?  Were you able to resolve all of the issues you encountered?
